import re

with open('src/generated/intelligence-api/types.gen.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# Find all Data types with url field using a stack-based brace matcher
def find_data_types(text):
    results = []
    pattern = r'export type (\w+Data) = \{'
    for m in re.finditer(pattern, text):
        name = m.group(1)
        # Find matching closing brace
        i = m.end() - 1
        depth = 1
        while i < len(text) and depth > 0:
            i += 1
            if text[i] == '{':
                depth += 1
            elif text[i] == '}':
                depth -= 1
        block = text[m.end()-1:i+1]
        # Extract url from block
        url_match = re.search(r"url: '([^']+)'", block)
        if url_match:
            results.append((name, url_match.group(1)))
    return results

matches = find_data_types(content)

# Determine HTTP method from type name
method_map = {
    'PostData': 'post',
    'GetData': 'get',
    'PutData': 'put',
    'PatchData': 'patch',
    'DeleteData': 'delete',
}

def get_method(name):
    for suffix, method in method_map.items():
        if name.endswith(suffix):
            return method
    return 'post'

def get_response_type(name):
    return name.replace('Data', 'Responses')

def get_error_type(name):
    return name.replace('Data', 'Errors')

# Build sdk.gen.ts content
lines = [
    '// This file is auto-generated by @hey-api/openapi-ts',
    '',
    "import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';",
    "import { client } from './client.gen';",
]

# Collect imports
import_types = []
for name, url in matches:
    import_types.append(name)
    resp = get_response_type(name)
    err = get_error_type(name)
    if resp not in import_types:
        import_types.append(resp)
    if err not in import_types:
        import_types.append(err)

lines.append(f"import type {{ {', '.join(import_types)} }} from './types.gen';")
lines.append('')
lines.append('export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {')
lines.append('    client?: Client;')
lines.append('    meta?: Record<string, unknown>;')
lines.append('};')
lines.append('')

# Generate route functions
for name, url in matches:
    method = get_method(name)
    func_name = name.replace('Data', '')
    func_name = func_name[0].lower() + func_name[1:]
    resp_type = get_response_type(name)
    err_type = get_error_type(name)
    
    # Check if multipart (has Body... type in the Data)
    body_type_name = name.replace('Data', '').replace('Route', '')
    # Simple heuristic: if url contains parse-file, ocr-fill, oppm-extract, use formDataBodySerializer
    needs_formdata = any(x in url for x in ['parse-file', 'ocr-fill', 'oppm-extract'])
    
    lines.append(f'export const {func_name} = <ThrowOnError extends boolean = false>(options: Options<{name}, ThrowOnError>) => (options.client ?? client).{method}<{resp_type}, {err_type}, ThrowOnError>({{')
    if needs_formdata:
        lines.append('    ...formDataBodySerializer,')
    lines.append("    security: [{ scheme: 'bearer', type: 'http' }],")
    lines.append(f"    url: '{url}',")
    lines.append('    ...options,')
    if needs_formdata:
        lines.append("    headers: {")
        lines.append("        'Content-Type': null,")
        lines.append('        ...options.headers')
        lines.append('    }')
    else:
        lines.append("    headers: {")
        lines.append("        'Content-Type': 'application/json',")
        lines.append('        ...options.headers')
        lines.append('    }')
    lines.append('});')
    lines.append('')

with open('src/generated/intelligence-api/sdk.gen.ts', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print('Generated sdk.gen.ts with', len(matches), 'routes')
